const wordList = [
  `it's about March 213th`,
  `amazon prime`,
  `Among Us`,
  `antibodies`,
  `asymptomatic`,
  `at least 6 feet`,
  `baby Yoda`,
  `ballot`,
  `Blursday`,
  `bubble`,
  `cancelled`,
  `Carole Baskin`,
  `Clorox wipes`,
  `contact tracing`,
  `Coronavirus`,
  `COVID-19`,
  `disinfect`,
  `doggface208`,
  `doomscroll`,
  `doomscrolling`,
  `Dr. Fauci`,
  `drive-in`,
  `Drizly`,
  `droplet`,
  `dumpster fire`,
  `election`,
  `essential`,
  `flatten the curve`,
  `Folklore`,
  `four seasons total landscaping`,
  `frontline workers`,
  `furlough`,
  `herd immunity`,
  `hindsight`,
  `home`,
  `home haircut`,
  `home office`,
  `home school`,
  `hurricane Greek alphabet`,
  `hybrid`,
  `hydroxychloroquine`,
  `into quarantine`,
  `isolation`,
  `Joe Exotic`,
  `K-shaped recovery`,
  `kraken`,
  `Last Dance`,
  `lockdown`,
  `Lysol spray`,
  `mail-in vote`,
  `mask`,
  `maskne`,
  `monolith`,
  `Mr. Peanut`,
  `murder hornets`,
  `my camera is off`,
  `N95`,
  `Netflix`,
  `no march madness`,
  `pandemic`,
  `pod`,
  `postponed`,
  `PPE`,
  `press conference`,
  `protests`,
  `quaranteam`,
  `quarantine`,
  `quarantini`,
  `Queen's Gambit`,
  `Quibi`,
  `remote`,
  `remote learning`,
  `sanitizer`,
  `schadenfreude`,
  `second wave`,
  `self care`,
  `shortage`,
  `social distance`,
  `social distancing`,
  `sourdough bread`,
  `spread`,
  `stay-at-home order`,
  `staycation`,
  `stimulus`,
  `storm Area 51`,
  `super-spreader event`,
  `sweatpants`,
  `take out order`,
  `the before times`,
  `the new normal`,
  `this claim is disputed`,
  `Tiger King`,
  `TikTok`,
  `toilet paper`,
  `trying times`,
  `UFO`,
  `uncertain times`,
  `unprecedented`,
  `vaccine`,
  `ventilator`,
  `virtual`,
  `virtual happy hour`,
  `vote`,
  `walktail`,
  `wash hands`,
  `we can't hear you.`,
  `wear a mask`,
  `what day is it?`,
  `whipped coffee`,
  `WHO`,
  `wildfires`,
  `working from home`,
  `X Æ A-Xii`,
  `you're on mute.`,
  `Zoom call`,
  `zoombomb`,
]

export default wordList;